# Generated by Django 5.1 on 2024-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('carteg_image', models.ImageField(blank=True, upload_to='photos/cartegories')),
            ],
            options={
                'verbose_name': 'cartegory',
                'verbose_name_plural': 'cartegories',
            },
        ),
    ]
