# Generated by Django 5.1 on 2024-11-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartegory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartegory',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
